package nginx

import (
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/jozefcipa/novus/internal/brew"
	"github.com/jozefcipa/novus/internal/config"
	"github.com/jozefcipa/novus/internal/logger"
)

const nginxServersDir = "/opt/homebrew/etc/nginx/servers"

func Start() {
	brew.StartBrewService("nginx")
}

func Stop() {
	brew.StopBrewService("nginx")
}

func Configure(config config.NovusConfig) {
	appName := "default"
	nginxConf := readServerConfig(appName)
	newNginxConf := buildServerConfig(config)

	if nginxConf == "" || nginxConf != newNginxConf {
		writeServerConfig(appName, newNginxConf)
		// fmt.Println(newNginxConf) TODO show this when debug is enabled
		logger.Messagef(" ✔ Routing configuration updated.\n")

		// TODO: restart nginx
		logger.Messagef(" ✔ Nginx reloaded.\n")
	} else {
		logger.Messagef(" ✔ Nginx config is up to date.\n")
	}

	logger.Messagef("🚀 Starting routing...\n")
	for _, route := range config.Routes {
		logger.Infof("  - http://%s -> ", route.Upstream)
		logger.Successf("https://%s\n", route.Url)
	}
}

func readServerConfig(app string) string {
	file, err := os.ReadFile(fmt.Sprintf("%s/novus-%s.conf", nginxServersDir, app))
	if err != nil {
		return ""
	}

	return string(file[:])
}

func writeServerConfig(app string, serverConfig string) {
	data := []byte(serverConfig)

	err := os.WriteFile(fmt.Sprintf("%s/novus-%s.conf", nginxServersDir, app), data, 0644)
	if err != nil {
		log.Fatalf("Failed to write into Nginx config: %v", err)
	}
}

func buildServerConfig(config config.NovusConfig) string {
	cwd, err := os.Getwd()
	if err != nil {
		log.Fatalf("Failed to get current working directory: %v\n", err)
	}

	f, err := os.ReadFile("./assets/nginx/server.template.conf")
	if err != nil {
		log.Fatalf("Failed to read server.template.conf file: %v", err)
	}

	serverConfigTemplate := string(f[:])

	// Add a header comment
	serverConfig := "# DO NOT EDIT THIS FILE!!!\n# This configuration is auto-generated by `novus`\n\n"

	// Iterate through all the routes and generate Nginx config
	for _, route := range config.Routes {
		routeConfig := strings.Replace(serverConfigTemplate, "--SERVER_NAME--", route.Url, -1)
		routeConfig = strings.Replace(routeConfig, "--PORT--", "80", -1)
		routeConfig = strings.Replace(routeConfig, "--UPSTREAM_ADDR--", route.Upstream, -1)
		routeConfig = strings.Replace(routeConfig, "--ERRORS_DIR--", cwd+"/assets/nginx", -1)

		serverConfig += routeConfig + "\n"
	}

	return serverConfig
}

// check if running
// `brew services info nginx --json`

// `nginx -t`` - validate configuration

// /opt/homebrew/etc/nginx/servers/nginx.conf - main config
// /opt/homebrew/etc/nginx/servers/* - directory of loaded configs, prefix our configs with novus-*
